# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0005_category_comments_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
